### ISSUE TITLE
API Key test failed

### ISSUE THREAD

**Issue by tomasz1986** [blabes/TrayTemperature#7]
When trying to test a newly generated API key, I get the following error.

```
Time: 
Error: Host requires authentication
Request: http://api.openweathermap.org/data/2.5/weather?lat=0&lon=0&appid=566dd...
```

I have tried with two different API keys, but the result was always this error. Of course, in this state the program is unable to obtain any weather data too.

**Comment by blabes** [comment]
This seems like it might be an issue with your particular API key; to test, can you please:

1. copy your API key from here: https://home.openweathermap.org/api_keys
2. create a URL using that API key and try it from your browser: http://api.openweathermap.org/data/2.5/weather?q=London&appid={APIkey}

If you get weather data for London (probably rainy and cloudy!) we'll at least know that your API key is working correctly outside of TrayTemperature.

FYI, it did take about a day for my free API key to become active, even after I received the welcome email from OpenWeather.

**Comment by ryanlowdermilk** [comment]
Having the same problem. I suspect, as indicated above, that it is simply a delay in my API key being activated.

**Comment by tomasz1986** [comment]
Yeah, I was too impatient. The API is working fine now. I'm sorry for the noise.
